#!/bin/sh

if [ $ARPA_OFF ]; then
  sed -i "s/^\(arpa\ *=\)/#\1/" "$CONF_FILE"
  sed -i "s/^\(locale\ *=\)/#\1/" "$CONF_FILE"
fi

/usr/bin/gunicorn $GUNICORN_RELOAD -w $GUNICORN_WORKER_AMOUNT -b 0.0.0.0:5000 run:app